### ISSUE TITLE
FSM

### ISSUE THREAD

**Issue by erynsmith** [sparkfun/Servo_Trigger#4]
I can't seem to get the FSM's to load properly
on lines 825 and 829, I changed the names to "bistableFSM" and "oneshotFSM"

do I need to do something else in the Atmel Studio?

**Comment by Jacquot-SFE** [comment]
As noted in the comments at the top of the source file:

>  The FSMs are selected by defining compile-time macros in the build scripts. 
>  To change functions, find the -D directives, and set them to the names of the
>  desired functions. 
>  In AVRStudio, this is in the project tab->toolchain->AVR/GNU C compiler->symbols dialog. 
>  In the command-line AVR-GCC, it's in the *.c->*.o rule in the makefile.
>  
>  You can select the FSMs for the two slots by changing the definition of the "FSMA" and
>  "FSMB" macros.  These macros should be set to the name of the FSM function for the desired slot.
>  There are several candidate FSM names:
>   - bistableFSM
>   - oneshotFSM
>   - ctpFSM
>   - togglingFSM
>   - astableFSM
>
